export const displayNames = {
  0: "Electron Beam Lithography Control",
  1: "Monitor",
  2: "Electron Beam Lithography",
  3: "EBL_a",
  4: "EBL_b",
  5: "EBE_control",
  6: "Electron Beam Evaporator",
  7: "EBE_a",
  8: "EBE_b",
  9: "Electron Beam Evaporator",
  10: "EBE_2_a",
  11: "EBE_2_b",
  12: "Scanning Electron Microscope",
  13: "SEM_a",
  14: "SEM_control",
  15: "SEM_control_a",
  16: "Dry Etching Tool",
  17: "dry_etching_a",
  18: "dry_etching_b",
  19: "Microscope",
  20: "Mask Aligner",
  21: "Spin Coater",
  22: "Fume Hood (Wet Bench)",
  23: "Hot Plate",
  24: "Oven",
  25: "Ultrasonic Bath",
  26: "Gown Rack",
  27: "Gear Rack",
  28: "Shower",
  29: "Spill Control Station",
  30: "Chemical Cabinet",
  31: "Furnace",
  32: "Pump",
  33: "First Aid Kit",
  34: "Fume Hood",
  35: "Electron Beam Evaporator",
  36: "EBE_3_a",
  37: "EBE_3_b"
};